/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'status' : AssignmentStatus,
  'date' : string,
  'crewMemberId' : Principal,
  'carOwnerId' : Principal,
}
export type AssignmentStatus = { 'pending' : null } |
  { 'skipped' : null } |
  { 'done' : null };
export interface CarOwnerProfile {
  'carModel' : string,
  'name' : string,
  'email' : string,
  'subscriptionActive' : boolean,
  'carNumber' : string,
  'priceSegment' : bigint,
  'carType' : CarType,
  'phone' : string,
  'registrationDate' : bigint,
}
export type CarType = { 'SUV' : null } |
  { 'midSUV' : null } |
  { 'sedan' : null } |
  { 'hatchback' : null };
export interface CrewMemberProfile {
  'name' : string,
  'isActive' : boolean,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBulkAssignments' : ActorMethod<
    [Array<[Principal, Principal]>],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCarOwnerToCrewMember' : ActorMethod<
    [Principal, Principal, string],
    undefined
  >,
  'getActiveCarOwners' : ActorMethod<
    [],
    [Array<[Principal, CarOwnerProfile]>, bigint]
  >,
  'getActiveCrewMembers' : ActorMethod<
    [],
    [Array<[Principal, CrewMemberProfile]>, bigint]
  >,
  'getAllCarOwners' : ActorMethod<[], Array<CarOwnerProfile>>,
  'getAllCrewMembers' : ActorMethod<[], Array<CrewMemberProfile>>,
  'getAssignmentsForCrewMember' : ActorMethod<
    [Principal, string],
    Array<Assignment>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCarOwnerProfile' : ActorMethod<[Principal], CarOwnerProfile>,
  'getCrewMemberProfile' : ActorMethod<[Principal], CrewMemberProfile>,
  'getDailySchedule' : ActorMethod<[string], Array<Assignment>>,
  'getScheduleForUser' : ActorMethod<[Principal], Array<Assignment>>,
  'getSkipDays' : ActorMethod<[Principal], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAssignmentDone' : ActorMethod<[Principal, string], undefined>,
  'registerCarOwner' : ActorMethod<
    [string, string, string, string, string, CarType],
    undefined
  >,
  'registerCrewMember' : ActorMethod<[string, string], undefined>,
  'skipDay' : ActorMethod<[string], undefined>,
  'updateAssignmentStatus' : ActorMethod<
    [Principal, string, AssignmentStatus],
    undefined
  >,
  'updateSubscriptionStatus' : ActorMethod<[string], undefined>,
  'wipeAllSkipDays' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];