/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CarType = IDL.Variant({
  'SUV' : IDL.Null,
  'midSUV' : IDL.Null,
  'sedan' : IDL.Null,
  'hatchback' : IDL.Null,
});
export const CarOwnerProfile = IDL.Record({
  'carModel' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'subscriptionActive' : IDL.Bool,
  'carNumber' : IDL.Text,
  'priceSegment' : IDL.Nat,
  'carType' : CarType,
  'phone' : IDL.Text,
  'registrationDate' : IDL.Int,
});
export const CrewMemberProfile = IDL.Record({
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'phone' : IDL.Text,
});
export const AssignmentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'skipped' : IDL.Null,
  'done' : IDL.Null,
});
export const Assignment = IDL.Record({
  'status' : AssignmentStatus,
  'date' : IDL.Text,
  'crewMemberId' : IDL.Principal,
  'carOwnerId' : IDL.Principal,
});
export const PaymentRecord = IDL.Record({
  'status' : IDL.Text,
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBulkAssignments' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal))],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCarOwnerToCrewMember' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Text],
      [],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getActiveCarOwners' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, CarOwnerProfile)), IDL.Nat],
      ['query'],
    ),
  'getActiveCrewMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, CrewMemberProfile)), IDL.Nat],
      ['query'],
    ),
  'getAllCarOwners' : IDL.Func([], [IDL.Vec(CarOwnerProfile)], ['query']),
  'getAllCrewMembers' : IDL.Func([], [IDL.Vec(CrewMemberProfile)], ['query']),
  'getAssignmentsForCrewMember' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCarOwnerProfile' : IDL.Func(
      [IDL.Principal],
      [CarOwnerProfile],
      ['query'],
    ),
  'getCrewMemberProfile' : IDL.Func(
      [IDL.Principal],
      [CrewMemberProfile],
      ['query'],
    ),
  'getDailySchedule' : IDL.Func([IDL.Text], [IDL.Vec(Assignment)], ['query']),
  'getPaymentHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getScheduleForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getSkipDays' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markAssignmentDone' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'recordPayment' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'registerCarOwner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, CarType],
      [],
      [],
    ),
  'registerCrewMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'skipDay' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAssignmentStatus' : IDL.Func(
      [IDL.Principal, IDL.Text, AssignmentStatus],
      [],
      [],
    ),
  'updateSubscriptionStatus' : IDL.Func([IDL.Text], [], []),
  'wipeAllSkipDays' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CarType = IDL.Variant({
    'SUV' : IDL.Null,
    'midSUV' : IDL.Null,
    'sedan' : IDL.Null,
    'hatchback' : IDL.Null,
  });
  const CarOwnerProfile = IDL.Record({
    'carModel' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'subscriptionActive' : IDL.Bool,
    'carNumber' : IDL.Text,
    'priceSegment' : IDL.Nat,
    'carType' : CarType,
    'phone' : IDL.Text,
    'registrationDate' : IDL.Int,
  });
  const CrewMemberProfile = IDL.Record({
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const AssignmentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'skipped' : IDL.Null,
    'done' : IDL.Null,
  });
  const Assignment = IDL.Record({
    'status' : AssignmentStatus,
    'date' : IDL.Text,
    'crewMemberId' : IDL.Principal,
    'carOwnerId' : IDL.Principal,
  });
  const PaymentRecord = IDL.Record({
    'status' : IDL.Text,
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBulkAssignments' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal))],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCarOwnerToCrewMember' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getActiveCarOwners' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, CarOwnerProfile)), IDL.Nat],
        ['query'],
      ),
    'getActiveCrewMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, CrewMemberProfile)), IDL.Nat],
        ['query'],
      ),
    'getAllCarOwners' : IDL.Func([], [IDL.Vec(CarOwnerProfile)], ['query']),
    'getAllCrewMembers' : IDL.Func([], [IDL.Vec(CrewMemberProfile)], ['query']),
    'getAssignmentsForCrewMember' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCarOwnerProfile' : IDL.Func(
        [IDL.Principal],
        [CarOwnerProfile],
        ['query'],
      ),
    'getCrewMemberProfile' : IDL.Func(
        [IDL.Principal],
        [CrewMemberProfile],
        ['query'],
      ),
    'getDailySchedule' : IDL.Func([IDL.Text], [IDL.Vec(Assignment)], ['query']),
    'getPaymentHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getScheduleForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getSkipDays' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markAssignmentDone' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'recordPayment' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerCarOwner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, CarType],
        [],
        [],
      ),
    'registerCrewMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'skipDay' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAssignmentStatus' : IDL.Func(
        [IDL.Principal, IDL.Text, AssignmentStatus],
        [],
        [],
      ),
    'updateSubscriptionStatus' : IDL.Func([IDL.Text], [], []),
    'wipeAllSkipDays' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };