/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'status' : AssignmentStatus,
  'date' : string,
  'crewMemberId' : Principal,
  'carOwnerId' : Principal,
}
export type AssignmentStatus = { 'pending' : null } |
  { 'skipped' : null } |
  { 'done' : null };
export interface CarOwnerProfile {
  'carModel' : string,
  'name' : string,
  'email' : string,
  'subscriptionActive' : boolean,
  'carNumber' : string,
  'priceSegment' : bigint,
  'carType' : CarType,
  'phone' : string,
  'registrationDate' : bigint,
}
export type CarType = { 'SUV' : null } |
  { 'midSUV' : null } |
  { 'sedan' : null } |
  { 'hatchback' : null };
export interface CrewMemberProfile {
  'name' : string,
  'isActive' : boolean,
  'phone' : string,
}
export interface PaymentRecord {
  'status' : string,
  'currency' : string,
  'timestamp' : bigint,
  'sessionId' : string,
  'amount' : bigint,
}
export interface WaitlistEntry {
  'name' : string,
  'email' : string,
  'phone' : string,
  'carModel' : string,
  'sectorSociety' : string,
  'carsInFamily' : bigint,
  'submittedAt' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBulkAssignments' : ActorMethod<
    [Array<[Principal, Principal]>],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCarOwnerToCrewMember' : ActorMethod<
    [Principal, Principal, string],
    undefined
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getActiveCarOwners' : ActorMethod<
    [],
    [Array<[Principal, CarOwnerProfile]>, bigint]
  >,
  'getActiveCrewMembers' : ActorMethod<
    [],
    [Array<[Principal, CrewMemberProfile]>, bigint]
  >,
  'getAllCarOwners' : ActorMethod<[], Array<CarOwnerProfile>>,
  'getAllCrewMembers' : ActorMethod<[], Array<CrewMemberProfile>>,
  'getAssignmentsForCrewMember' : ActorMethod<
    [Principal, string],
    Array<Assignment>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCarOwnerProfile' : ActorMethod<[Principal], CarOwnerProfile>,
  'getCrewMemberProfile' : ActorMethod<[Principal], CrewMemberProfile>,
  'getDailySchedule' : ActorMethod<[string], Array<Assignment>>,
  'getPaymentHistory' : ActorMethod<[Principal], Array<PaymentRecord>>,
  'getScheduleForUser' : ActorMethod<[Principal], Array<Assignment>>,
  'getSkipDays' : ActorMethod<[Principal], Array<string>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getWaitlistCount' : ActorMethod<[], bigint>,
  'getWaitlistEntries' : ActorMethod<[], Array<WaitlistEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markAssignmentDone' : ActorMethod<[Principal, string], undefined>,
  'recordPayment' : ActorMethod<[Principal, bigint, string, string], undefined>,
  'registerCarOwner' : ActorMethod<
    [string, string, string, string, string, CarType],
    undefined
  >,
  'registerCrewMember' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'skipDay' : ActorMethod<[string], undefined>,
  'submitWaitlist' : ActorMethod<[string, string, string, string, string, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAssignmentStatus' : ActorMethod<
    [Principal, string, AssignmentStatus],
    undefined
  >,
  'updateSubscriptionStatus' : ActorMethod<[string], undefined>,
  'wipeAllSkipDays' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];