/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CarType = IDL.Variant({
  'SUV' : IDL.Null,
  'midSUV' : IDL.Null,
  'sedan' : IDL.Null,
  'hatchback' : IDL.Null,
});
export const CarOwnerProfile = IDL.Record({
  'carModel' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'subscriptionActive' : IDL.Bool,
  'carNumber' : IDL.Text,
  'priceSegment' : IDL.Nat,
  'carType' : CarType,
  'phone' : IDL.Text,
  'registrationDate' : IDL.Int,
});
export const CrewMemberProfile = IDL.Record({
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'phone' : IDL.Text,
});
export const AssignmentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'skipped' : IDL.Null,
  'done' : IDL.Null,
});
export const Assignment = IDL.Record({
  'status' : AssignmentStatus,
  'date' : IDL.Text,
  'crewMemberId' : IDL.Principal,
  'carOwnerId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBulkAssignments' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal))],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCarOwnerToCrewMember' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Text],
      [],
      [],
    ),
  'getActiveCarOwners' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, CarOwnerProfile)), IDL.Nat],
      ['query'],
    ),
  'getActiveCrewMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, CrewMemberProfile)), IDL.Nat],
      ['query'],
    ),
  'getAllCarOwners' : IDL.Func([], [IDL.Vec(CarOwnerProfile)], ['query']),
  'getAllCrewMembers' : IDL.Func([], [IDL.Vec(CrewMemberProfile)], ['query']),
  'getAssignmentsForCrewMember' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCarOwnerProfile' : IDL.Func(
      [IDL.Principal],
      [CarOwnerProfile],
      ['query'],
    ),
  'getCrewMemberProfile' : IDL.Func(
      [IDL.Principal],
      [CrewMemberProfile],
      ['query'],
    ),
  'getDailySchedule' : IDL.Func([IDL.Text], [IDL.Vec(Assignment)], ['query']),
  'getScheduleForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getSkipDays' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAssignmentDone' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'registerCarOwner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, CarType],
      [],
      [],
    ),
  'registerCrewMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'skipDay' : IDL.Func([IDL.Text], [], []),
  'updateAssignmentStatus' : IDL.Func(
      [IDL.Principal, IDL.Text, AssignmentStatus],
      [],
      [],
    ),
  'updateSubscriptionStatus' : IDL.Func([IDL.Text], [], []),
  'wipeAllSkipDays' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CarType = IDL.Variant({
    'SUV' : IDL.Null,
    'midSUV' : IDL.Null,
    'sedan' : IDL.Null,
    'hatchback' : IDL.Null,
  });
  const CarOwnerProfile = IDL.Record({
    'carModel' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'subscriptionActive' : IDL.Bool,
    'carNumber' : IDL.Text,
    'priceSegment' : IDL.Nat,
    'carType' : CarType,
    'phone' : IDL.Text,
    'registrationDate' : IDL.Int,
  });
  const CrewMemberProfile = IDL.Record({
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const AssignmentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'skipped' : IDL.Null,
    'done' : IDL.Null,
  });
  const Assignment = IDL.Record({
    'status' : AssignmentStatus,
    'date' : IDL.Text,
    'crewMemberId' : IDL.Principal,
    'carOwnerId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBulkAssignments' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal))],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCarOwnerToCrewMember' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'getActiveCarOwners' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, CarOwnerProfile)), IDL.Nat],
        ['query'],
      ),
    'getActiveCrewMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, CrewMemberProfile)), IDL.Nat],
        ['query'],
      ),
    'getAllCarOwners' : IDL.Func([], [IDL.Vec(CarOwnerProfile)], ['query']),
    'getAllCrewMembers' : IDL.Func([], [IDL.Vec(CrewMemberProfile)], ['query']),
    'getAssignmentsForCrewMember' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCarOwnerProfile' : IDL.Func(
        [IDL.Principal],
        [CarOwnerProfile],
        ['query'],
      ),
    'getCrewMemberProfile' : IDL.Func(
        [IDL.Principal],
        [CrewMemberProfile],
        ['query'],
      ),
    'getDailySchedule' : IDL.Func([IDL.Text], [IDL.Vec(Assignment)], ['query']),
    'getScheduleForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getSkipDays' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAssignmentDone' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'registerCarOwner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, CarType],
        [],
        [],
      ),
    'registerCrewMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'skipDay' : IDL.Func([IDL.Text], [], []),
    'updateAssignmentStatus' : IDL.Func(
        [IDL.Principal, IDL.Text, AssignmentStatus],
        [],
        [],
      ),
    'updateSubscriptionStatus' : IDL.Func([IDL.Text], [], []),
    'wipeAllSkipDays' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };