/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Assignment {
    status: AssignmentStatus;
    date: string;
    crewMemberId: Principal;
    carOwnerId: Principal;
}
export interface CarOwnerProfile {
    carModel: string;
    name: string;
    email: string;
    subscriptionActive: boolean;
    carNumber: string;
    priceSegment: bigint;
    carType: CarType;
    phone: string;
    registrationDate: bigint;
}
export interface CrewMemberProfile {
    name: string;
    isActive: boolean;
    phone: string;
}
export enum AssignmentStatus {
    pending = "pending",
    skipped = "skipped",
    done = "done"
}
export enum CarType {
    SUV = "SUV",
    midSUV = "midSUV",
    sedan = "sedan",
    hatchback = "hatchback"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBulkAssignments(newAssignments: Array<[Principal, Principal]>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignCarOwnerToCrewMember(carOwnerId: Principal, crewMemberId: Principal, date: string): Promise<void>;
    getActiveCarOwners(): Promise<[Array<[Principal, CarOwnerProfile]>, bigint]>;
    getActiveCrewMembers(): Promise<[Array<[Principal, CrewMemberProfile]>, bigint]>;
    getAllCarOwners(): Promise<Array<CarOwnerProfile>>;
    getAllCrewMembers(): Promise<Array<CrewMemberProfile>>;
    getAssignmentsForCrewMember(crewMemberId: Principal, date: string): Promise<Array<Assignment>>;
    getCallerUserRole(): Promise<UserRole>;
    getCarOwnerProfile(id: Principal): Promise<CarOwnerProfile>;
    getCrewMemberProfile(id: Principal): Promise<CrewMemberProfile>;
    getDailySchedule(date: string): Promise<Array<Assignment>>;
    getScheduleForUser(user: Principal): Promise<Array<Assignment>>;
    getSkipDays(user: Principal): Promise<Array<string>>;
    isCallerAdmin(): Promise<boolean>;
    markAssignmentDone(carOwnerId: Principal, date: string): Promise<void>;
    registerCarOwner(name: string, email: string, phone: string, carNumber: string, carModel: string, carType: CarType): Promise<void>;
    registerCrewMember(name: string, phone: string): Promise<void>;
    skipDay(date: string): Promise<void>;
    updateAssignmentStatus(carOwnerId: Principal, date: string, newStatus: AssignmentStatus): Promise<void>;
    updateSubscriptionStatus(action: string): Promise<void>;
    wipeAllSkipDays(): Promise<void>;
}
import type { Assignment as _Assignment, AssignmentStatus as _AssignmentStatus, CarOwnerProfile as _CarOwnerProfile, CarType as _CarType, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBulkAssignments(arg0: Array<[Principal, Principal]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkAssignments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkAssignments(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCarOwnerToCrewMember(arg0: Principal, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCarOwnerToCrewMember(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCarOwnerToCrewMember(arg0, arg1, arg2);
            return result;
        }
    }
    async getActiveCarOwners(): Promise<[Array<[Principal, CarOwnerProfile]>, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCarOwners();
                return [
                    from_candid_vec_n3(this._uploadFile, this._downloadFile, result[0]),
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCarOwners();
            return [
                from_candid_vec_n3(this._uploadFile, this._downloadFile, result[0]),
                result[1]
            ];
        }
    }
    async getActiveCrewMembers(): Promise<[Array<[Principal, CrewMemberProfile]>, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCrewMembers();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCrewMembers();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getAllCarOwners(): Promise<Array<CarOwnerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCarOwners();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCarOwners();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCrewMembers(): Promise<Array<CrewMemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCrewMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCrewMembers();
            return result;
        }
    }
    async getAssignmentsForCrewMember(arg0: Principal, arg1: string): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentsForCrewMember(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentsForCrewMember(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarOwnerProfile(arg0: Principal): Promise<CarOwnerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarOwnerProfile(arg0);
                return from_candid_CarOwnerProfile_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarOwnerProfile(arg0);
            return from_candid_CarOwnerProfile_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrewMemberProfile(arg0: Principal): Promise<CrewMemberProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrewMemberProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrewMemberProfile(arg0);
            return result;
        }
    }
    async getDailySchedule(arg0: string): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySchedule(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySchedule(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScheduleForUser(arg0: Principal): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduleForUser(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduleForUser(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkipDays(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkipDays(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkipDays(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAssignmentDone(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAssignmentDone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAssignmentDone(arg0, arg1);
            return result;
        }
    }
    async registerCarOwner(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: CarType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCarOwner(arg0, arg1, arg2, arg3, arg4, to_candid_CarType_n17(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCarOwner(arg0, arg1, arg2, arg3, arg4, to_candid_CarType_n17(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async registerCrewMember(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCrewMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCrewMember(arg0, arg1);
            return result;
        }
    }
    async skipDay(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.skipDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.skipDay(arg0);
            return result;
        }
    }
    async updateAssignmentStatus(arg0: Principal, arg1: string, arg2: AssignmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssignmentStatus(arg0, arg1, to_candid_AssignmentStatus_n19(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssignmentStatus(arg0, arg1, to_candid_AssignmentStatus_n19(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSubscriptionStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionStatus(arg0);
            return result;
        }
    }
    async wipeAllSkipDays(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.wipeAllSkipDays();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.wipeAllSkipDays();
            return result;
        }
    }
}
function from_candid_AssignmentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentStatus): AssignmentStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Assignment_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CarOwnerProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarOwnerProfile): CarOwnerProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CarType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarType): CarType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AssignmentStatus;
    date: string;
    crewMemberId: Principal;
    carOwnerId: Principal;
}): {
    status: AssignmentStatus;
    date: string;
    crewMemberId: Principal;
    carOwnerId: Principal;
} {
    return {
        status: from_candid_AssignmentStatus_n13(_uploadFile, _downloadFile, value.status),
        date: value.date,
        crewMemberId: value.crewMemberId,
        carOwnerId: value.carOwnerId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    carModel: string;
    name: string;
    email: string;
    subscriptionActive: boolean;
    carNumber: string;
    priceSegment: bigint;
    carType: _CarType;
    phone: string;
    registrationDate: bigint;
}): {
    carModel: string;
    name: string;
    email: string;
    subscriptionActive: boolean;
    carNumber: string;
    priceSegment: bigint;
    carType: CarType;
    phone: string;
    registrationDate: bigint;
} {
    return {
        carModel: value.carModel,
        name: value.name,
        email: value.email,
        subscriptionActive: value.subscriptionActive,
        carNumber: value.carNumber,
        priceSegment: value.priceSegment,
        carType: from_candid_CarType_n7(_uploadFile, _downloadFile, value.carType),
        phone: value.phone,
        registrationDate: value.registrationDate
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _CarOwnerProfile]): [Principal, CarOwnerProfile] {
    return [
        value[0],
        from_candid_CarOwnerProfile_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    skipped: null;
} | {
    done: null;
}): AssignmentStatus {
    return "pending" in value ? AssignmentStatus.pending : "skipped" in value ? AssignmentStatus.skipped : "done" in value ? AssignmentStatus.done : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SUV: null;
} | {
    midSUV: null;
} | {
    sedan: null;
} | {
    hatchback: null;
}): CarType {
    return "SUV" in value ? CarType.SUV : "midSUV" in value ? CarType.midSUV : "sedan" in value ? CarType.sedan : "hatchback" in value ? CarType.hatchback : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _CarOwnerProfile]>): Array<[Principal, CarOwnerProfile]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CarOwnerProfile>): Array<CarOwnerProfile> {
    return value.map((x)=>from_candid_CarOwnerProfile_n5(_uploadFile, _downloadFile, x));
}
function to_candid_AssignmentStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentStatus): _AssignmentStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CarType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarType): _CarType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarType): {
    SUV: null;
} | {
    midSUV: null;
} | {
    sedan: null;
} | {
    hatchback: null;
} {
    return value == CarType.SUV ? {
        SUV: null
    } : value == CarType.midSUV ? {
        midSUV: null
    } : value == CarType.sedan ? {
        sedan: null
    } : value == CarType.hatchback ? {
        hatchback: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentStatus): {
    pending: null;
} | {
    skipped: null;
} | {
    done: null;
} {
    return value == AssignmentStatus.pending ? {
        pending: null
    } : value == AssignmentStatus.skipped ? {
        skipped: null
    } : value == AssignmentStatus.done ? {
        done: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
